<Project ToolsVersion="3.5" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />

  <PropertyGroup>
    <SaxonJar>$(ModuleDir)\tools\Saxon\saxon.jar</SaxonJar>

    <XslthlJar>$(ModuleDir)\tools\Xslthl\xslthl.jar</XslthlJar>
    <XslthlConfig>$(ModuleDir)\resources\Highlighters\xslthl-config.xml</XslthlConfig>

    <XercesJar>$(ModuleDir)\tools\xerces-2_9_1\xercesImpl.jar</XercesJar>

    <FopBat>$(ModuleDir)\tools\fop-0.94\fop.bat</FopBat>
    <FopConf>$(ModuleDir)\resources\Fo\Fop.xconf</FopConf>

    <BookXml>$(ModuleDir)\content\GallioBook.docbook</BookXml>

    <XHtmlXslt>$(ModuleDir)\resources\Html\XHtml.xsl</XHtmlXslt>
    <HtmlHelpXslt>$(ModuleDir)\resources\Html\HtmlHelp.xsl</HtmlHelpXslt>

    <PdfXslt>$(ModuleDir)\resources\Fo\Pdf.xsl</PdfXslt>

    <TransformCommand>java -cp &quot;$(SaxonJar)&quot;;&quot;$(XslthlJar)&quot;;&quot;$(XercesJar)&quot; -Djavax.xml.parsers.DocumentBuilderFactory=org.apache.xerces.jaxp.DocumentBuilderFactoryImpl -Djavax.xml.parsers.SAXParserFactory=org.apache.xerces.jaxp.SAXParserFactoryImpl -Dorg.apache.xerces.xni.parser.XMLParserConfiguration=org.apache.xerces.parsers.XIncludeParserConfiguration -Dxslthl.config=&quot;file:///$(XslthlConfig)&quot; com.icl.saxon.StyleSheet</TransformCommand>
  </PropertyGroup>

  <Target Name="AfterBuild"
          DependsOnTargets="RenderDocBookXHtml;RenderDocBookPdf;RenderDocBookHtmlHelp">
  </Target>

  <Target Name="RenderDocBookXHtml"
          DependsOnTargets="CopyContentForXHtml">
    <Message Text="Rendering Book in XHTML..." Importance="High" />

    <Exec Command="$(TransformCommand) -o &quot;c:\temp\foo.xml&quot; &quot;$(BookXml)&quot; &quot;c:\temp\template.xsl&quot;" />


    <Exec Command="$(TransformCommand) &quot;$(BookXml)&quot; &quot;$(XHtmlXslt)&quot; chunker.output.encoding=&quot;UTF-8&quot; chunker.output.indent=&quot;yes&quot; html.stylesheet=&quot;Book.css&quot; keep.relative.image.uris=0"
          WorkingDirectory="$(ImageDir)\GallioBook\XHtml" />
  </Target>

  <Target Name="RenderDocBookPdf">
    <Message Text="Rendering Book in PDF..." Importance="High" />

    <Exec Command="$(TransformCommand) -o &quot;$(TempDir)\GallioBook\GallioBook.fo&quot; &quot;$(BookXml)&quot; &quot;$(PdfXslt)&quot; keep.relative.image.uris=0" />
    <Exec Command="&quot;$(FopBat)&quot; -fo &quot;$(TempDir)\GallioBook\GallioBook.fo&quot; -c &quot;$(FopConf)&quot; -pdf &quot;$(ImageDir)\GallioBook\GallioBook.pdf&quot;"
          WorkingDirectory="content" />
  </Target>

  <Target Name="RenderDocBookHtmlHelp">
    <Message Text="Rendering Book in HtmlHelp (CHM)..." Importance="High" />

    <PropertyGroup>
      <HtmlHelpWorkshopInstallDir>$(Registry:HKEY_CURRENT_USER\Software\Microsoft\HTML Help Workshop\@InstallDir)</HtmlHelpWorkshopInstallDir>
      <HtmlHelpWorkshopInstallDir Condition="'HtmlHelpWorkshopInstallDir'==''">$(Registry:HKEY_LOCAL_MACHINE\Software\Microsoft\HTML Help Workshop\@InstallDir)</HtmlHelpWorkshopInstallDir>
    </PropertyGroup>

    <Warning Text="The HTML Help Workshop does not appear to be installed.  The documentation will not be rendered in this format."
             Condition="'$(HtmlHelpWorkshopInstallDir)'==''"/>

    <MakeDir Directories="$(TempDir)\GallioBook\HtmlHelp"
             Condition="'$(HtmlHelpWorkshopInstallDir)'!=''"/>

    <Exec Command="$(TransformCommand) &quot;$(BookXml)&quot; &quot;$(HtmlHelpXslt)&quot; html.stylesheet=&quot;Book.css&quot; htmlhelp.chm=&quot;$(ImageDir)\GallioBook\GallioBook.chm&quot; keep.relative.image.uris=0"
          WorkingDirectory="$(TempDir)\GallioBook\HtmlHelp"
          Condition="'$(HtmlHelpWorkshopInstallDir)'!=''"/>

    <Exec Command="&quot;$(HtmlHelpWorkshopInstallDir)\hhc.exe&quot; &quot;$(TempDir)\GallioBook\HtmlHelp\htmlhelp.hhp&quot;"
          WorkingDirectory="content"
          Condition="'$(HtmlHelpWorkshopInstallDir)'!=''"
	  IgnoreExitCode="true"/>

    <Error Text="CHM file not produced!"
           Condition="'$(HtmlHelpWorkshopInstallDir)'!='' and ! Exists('$(ImageDir)\GallioBook\GallioBook.chm')"/>
  </Target>

  <Target Name="CopyContentForXHtml">
    <RemoveDir Directories="$(ImageDir)\GallioBook\XHtml" />

    <SvnExport RepositoryPath="$(ModuleDir)\content"
               LocalPath="$(ImageDir)\GallioBook\XHtml" />
	       
    <ItemGroup>
      <_ContentFilesToDeleteForXHtml Include="$(ImageDir)\GallioBook\XHtml\**\*.docbook" />
    </ItemGroup>

    <Delete Files="@(_ContentFilesToDeleteForXHtml)"
            Condition="'@(_ContentFilesToDeleteForXHtml)'!=''" />
  </Target>
</Project>
