<Project ToolsVersion="3.5" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />

  <PropertyGroup>
    <SaxonJar>$(ModuleDir)\tools\Saxon\saxon.jar</SaxonJar>

    <XslthlJar>$(ModuleDir)\tools\Xslthl\xslthl.jar</XslthlJar>
    <XslthlConfig>$(ModuleDir)\resources\Highlighters\xslthl-config.xml</XslthlConfig>

    <FopBat>$(ModuleDir)\tools\fop-0.94\fop.bat</FopBat>
    <FopConf>$(ModuleDir)\resources\Fo\Fop.xconf</FopConf>

    <BookXml>$(ModuleDir)\content\GallioBook.en.xml</BookXml>

    <XHtmlXslt>$(ModuleDir)\resources\Html\XHtml.xsl</XHtmlXslt>
    <HtmlCss>$(ModuleDir)\resources\Html\GallioBook.css</HtmlCss>
    <HtmlHelpXslt>$(ModuleDir)\resources\Html\HtmlHelp.xsl</HtmlHelpXslt>

    <PdfXslt>$(ModuleDir)\resources\Fo\Pdf.xsl</PdfXslt>
  </PropertyGroup>

  <Target Name="AfterBuild"
          DependsOnTargets="RenderDocBookHtml;RenderDocBookPdf;RenderDocBookHtmlHelp">
  </Target>

  <Target Name="RenderDocBookHtml">
    <Message Text="Rendering Book in XHTML..." Importance="High" />

    <MakeDir Directories="$(ImageDir)\GallioBook\XHtml" />

    <Exec Command="java -cp &quot;$(SaxonJar)&quot;;&quot;$(XslthlJar)&quot; -Dxslthl.config=&quot;file:///$(XslthlConfig)&quot; com.icl.saxon.StyleSheet &quot;$(BookXml)&quot; &quot;$(XHtmlXslt)&quot; chunker.output.encoding=&quot;UTF-8&quot; chunker.output.indent=&quot;yes&quot; html.stylesheet=&quot;$(HtmlCss)&quot;"
          WorkingDirectory="$(ImageDir)\GallioBook\XHtml" />
  </Target>

  <Target Name="RenderDocBookPdf">
    <Message Text="Rendering Book in PDF..." Importance="High" />

    <Exec Command="java -cp &quot;$(SaxonJar)&quot;;&quot;$(XslthlJar)&quot; -Dxslthl.config=&quot;file:///$(XslthlConfig)&quot; com.icl.saxon.StyleSheet -o &quot;$(TempDir)\GallioBook\GallioBook.fo&quot; &quot;$(BookXml)&quot; &quot;$(PdfXslt)&quot;" />
    <Exec Command="&quot;$(FopBat)&quot; -fo &quot;$(TempDir)\GallioBook\GallioBook.fo&quot; -c &quot;$(FopConf)&quot; -pdf &quot;$(ImageDir)\GallioBook\GallioBook.pdf&quot;" />
  </Target>

  <Target Name="RenderDocBookHtmlHelp">
    <Message Text="Rendering Book in HtmlHelp (CHM)..." Importance="High" />

    <PropertyGroup>
      <HtmlHelpWorkshopInstallDir>$(Registry:HKEY_CURRENT_USER\Software\Microsoft\HTML Help Workshop\@InstallDir)</HtmlHelpWorkshopInstallDir>
      <HtmlHelpWorkshopInstallDir Condition="'HtmlHelpWorkshopInstallDir'==''">$(Registry:HKEY_LOCAL_MACHINE\Software\Microsoft\HTML Help Workshop\@InstallDir)</HtmlHelpWorkshopInstallDir>
    </PropertyGroup>

    <Warning Text="The HTML Help Workshop does not appear to be installed.  The documentation will not be rendered in this format."
             Condition="'$(HtmlHelpWorkshopInstallDir)'==''"/>

    <MakeDir Directories="$(TempDir)\GallioBook\HtmlHelp"
             Condition="'$(HtmlHelpWorkshopInstallDir)'!=''"/>

    <Exec Command="java -cp &quot;$(SaxonJar)&quot;;&quot;$(XslthlJar)&quot; -Dxslthl.config=&quot;file:///$(XslthlConfig)&quot; com.icl.saxon.StyleSheet &quot;$(BookXml)&quot; &quot;$(HtmlHelpXslt)&quot; html.stylesheet=&quot;$(HtmlCss)&quot; htmlhelp.chm=&quot;$(ImageDir)\GallioBook\GallioBook.chm&quot;"
          WorkingDirectory="$(TempDir)\GallioBook\HtmlHelp"
          Condition="'$(HtmlHelpWorkshopInstallDir)'!=''"/>

    <Exec Command="&quot;$(HtmlHelpWorkshopInstallDir)\hhc.exe&quot; &quot;$(TempDir)\GallioBook\HtmlHelp\htmlhelp.hhp&quot;"
          Condition="'$(HtmlHelpWorkshopInstallDir)'!=''"
	  IgnoreExitCode="true"/>

    <Error Text="CHM file not produced!"
           Condition="'$(HtmlHelpWorkshopInstallDir)'!='' and ! Exists('$(ImageDir)\GallioBook\GallioBook.chm')"/>
  </Target>
</Project>
